# exported from PySB model 'pysb'

from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

# s.spolaor@campus.unimib.it

Monomer('AA')
Monomer('Ca')
Monomer('DAG')
Monomer('MAPK_slash_MAPK')
Monomer('MAPK_slash_MAPKK')
Monomer('MAPK_slash_MAPKK_minus_ser')
Monomer('MAPK_slash_MAPKK_star_')
Monomer('MAPK_slash_MAPKK_star__slash_MAPKKthr_slash_MAPKKthr_cplx')
Monomer('MAPK_slash_MAPKK_star__slash_MAPKKtyr_slash_MAPKKtyr_cplx')
Monomer('MAPK_slash_MAPK_minus_tyr')
Monomer('MAPK_slash_Raf_minus_GTP_minus_Ras_star_')
Monomer('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_slash_Raf_minus_GTP_minus_Ras_star__dot_1_cplx')
Monomer('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_slash_Raf_minus_GTP_minus_Ras_star__dot_2_cplx')
Monomer('MAPK_slash_craf_minus_1')
Monomer('MAPK_slash_craf_minus_1_star_')
Monomer('MAPK_slash_craf_minus_1_star__star_')
Monomer('MAPK_star_')
Monomer('MAPK_star__slash_MAPK_star__minus_feedback_slash_MAPK_star__minus_feedback_cplx')
Monomer('MAPK_star__slash_MAPK_star__slash_MAPK_star__cplx')
Monomer('MKP_minus_1')
Monomer('MKP_minus_1_slash_MKP1_minus_thr_minus_deph_slash_MKP1_minus_thr_minus_deph_cplx')
Monomer('MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_slash_MKP1_minus_tyr_minus_deph_cplx')
Monomer('PKC_minus_active')
Monomer('PKC_minus_active_slash_PKC_minus_act_minus_GEF_slash_PKC_minus_act_minus_GEF_cplx')
Monomer('PKC_minus_active_slash_PKC_minus_act_minus_raf_slash_PKC_minus_act_minus_raf_cplx')
Monomer('PKC_minus_active_slash_PKC_minus_inact_minus_GAP_slash_PKC_minus_inact_minus_GAP_cplx')
Monomer('PKC_slash_PKC_minus_AA_star_')
Monomer('PKC_slash_PKC_minus_Ca')
Monomer('PKC_slash_PKC_minus_Ca_minus_AA_star_')
Monomer('PKC_slash_PKC_minus_Ca_minus_DAG')
Monomer('PKC_slash_PKC_minus_Ca_minus_memb_star_')
Monomer('PKC_slash_PKC_minus_DAG')
Monomer('PKC_slash_PKC_minus_DAG_minus_AA')
Monomer('PKC_slash_PKC_minus_DAG_minus_AA_star_')
Monomer('PKC_slash_PKC_minus_DAG_minus_memb_star_')
Monomer('PKC_slash_PKC_minus_basal_star_')
Monomer('PKC_slash_PKC_minus_cytosolic')
Monomer('PLA2_slash_APC')
Monomer('PLA2_slash_DAG_minus_Ca_minus_PLA2_star_')
Monomer('PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx')
Monomer('PLA2_slash_PIP2_minus_Ca_minus_PLA2_star_')
Monomer('PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx')
Monomer('PLA2_slash_PIP2_minus_PLA2_star_')
Monomer('PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_slash_kenz_cplx')
Monomer('PLA2_slash_PLA2_minus_Ca_star_')
Monomer('PLA2_slash_PLA2_minus_Ca_star__slash_kenz_slash_kenz_cplx')
Monomer('PLA2_slash_PLA2_minus_cytosolic')
Monomer('PLA2_slash_PLA2_star_')
Monomer('PLA2_slash_PLA2_star__minus_Ca')
Monomer('PLA2_slash_PLA2_star__minus_Ca_slash_kenz_slash_kenz_cplx')
Monomer('PPhosphatase2A')
Monomer('PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_slash_MAPKK_minus_deph_minus_ser_cplx')
Monomer('PPhosphatase2A_slash_MAPKK_minus_deph_slash_MAPKK_minus_deph_cplx')
Monomer('PPhosphatase2A_slash_craf_minus_deph_slash_craf_minus_deph_cplx')
Monomer('PPhosphatase2A_slash_craf_star__star__minus_deph_slash_craf_star__star__minus_deph_cplx')
Monomer('Ras_slash_GAP')
Monomer('Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_slash_GAP_minus_inact_minus_ras_cplx')
Monomer('Ras_slash_GAP_star_')
Monomer('Ras_slash_GDP_minus_Ras')
Monomer('Ras_slash_GEF_star_')
Monomer('Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_slash_GEF_star__minus_act_minus_ras_cplx')
Monomer('Ras_slash_GTP_minus_Ras')
Monomer('Ras_slash_inact_minus_GEF')
Monomer('temp_minus_PIP2')

Parameter('r1_kf', 0.0)
Parameter('r1_kb', 0.0)
Parameter('r2_kf', 0.0)
Parameter('r2_kb', 0.0)
Parameter('r3_kf', 0.0)
Parameter('r3_kb', 0.0)
Parameter('r4_kf', 0.0)
Parameter('r4_kb', 0.0)
Parameter('r5_kf', 0.0)
Parameter('r5_kb', 0.0)
Parameter('r6_kf', 0.0)
Parameter('r6_kb', 0.0)
Parameter('r7_kf', 0.0)
Parameter('r7_kb', 0.0)
Parameter('r8_kf', 0.0)
Parameter('r8_kb', 0.0)
Parameter('r9_kf', 0.0)
Parameter('r9_kb', 0.0)
Parameter('r10_kf', 0.0)
Parameter('r10_kb', 0.0)
Parameter('r11_kf', 0.0)
Parameter('r11_kb', 0.0)
Parameter('r12_kf', 0.0)
Parameter('r12_kb', 0.0)
Parameter('r13_kf', 0.0)
Parameter('r13_kb', 0.0)
Parameter('r14_kf', 0.0)
Parameter('r14_kb', 0.0)
Parameter('r15_kf', 0.0)
Parameter('r15_kb', 0.0)
Parameter('r16_kf', 0.0)
Parameter('r16_kb', 0.0)
Parameter('r17_kf', 0.0)
Parameter('r17_kb', 0.0)
Parameter('r18_kf', 0.0)
Parameter('r18_kb', 0.0)
Parameter('r19_kf', 0.0)
Parameter('r19_kb', 0.0)
Parameter('r20_kf', 0.0)
Parameter('r20_kb', 0.0)
Parameter('r21_kf', 0.0)
Parameter('r21_kb', 0.0)
Parameter('r22_k1', 0.0)
Parameter('r22_k2', 0.0)
Parameter('r23_k3', 0.0)
Parameter('r24_k1', 0.0)
Parameter('r24_k2', 0.0)
Parameter('r25_k3', 0.0)
Parameter('r26_k1', 0.0)
Parameter('r26_k2', 0.0)
Parameter('r27_k3', 0.0)
Parameter('r28_k1', 0.0)
Parameter('r28_k2', 0.0)
Parameter('r29_k3', 0.0)
Parameter('r30_k1', 0.0)
Parameter('r30_k2', 0.0)
Parameter('r31_k3', 0.0)
Parameter('r32_k1', 0.0)
Parameter('r32_k2', 0.0)
Parameter('r33_k3', 0.0)
Parameter('r34_k1', 0.0)
Parameter('r34_k2', 0.0)
Parameter('r35_k3', 0.0)
Parameter('r36_k1', 0.0)
Parameter('r36_k2', 0.0)
Parameter('r37_k3', 0.0)
Parameter('r38_k1', 0.0)
Parameter('r38_k2', 0.0)
Parameter('r39_k3', 0.0)
Parameter('r40_k1', 0.0)
Parameter('r40_k2', 0.0)
Parameter('r41_k3', 0.0)
Parameter('r42_k1', 0.0)
Parameter('r42_k2', 0.0)
Parameter('r43_k3', 0.0)
Parameter('r44_k1', 0.0)
Parameter('r44_k2', 0.0)
Parameter('r45_k3', 0.0)
Parameter('r46_k1', 0.0)
Parameter('r46_k2', 0.0)
Parameter('r47_k3', 0.0)
Parameter('r48_k1', 0.0)
Parameter('r48_k2', 0.0)
Parameter('r49_k3', 0.0)
Parameter('r50_k1', 0.0)
Parameter('r50_k2', 0.0)
Parameter('r51_k3', 0.0)
Parameter('r52_k1', 0.0)
Parameter('r52_k2', 0.0)
Parameter('r53_k3', 0.0)
Parameter('r54_k1', 0.0)
Parameter('r54_k2', 0.0)
Parameter('r55_k3', 0.0)
Parameter('r56_k1', 0.0)
Parameter('r56_k2', 0.0)
Parameter('r57_k3', 0.0)
Parameter('r58_k1', 0.0)
Parameter('r58_k2', 0.0)
Parameter('r59_k3', 0.0)
Parameter('r60_k1', 0.0)
Parameter('r60_k2', 0.0)
Parameter('r61_k3', 0.0)
Parameter('r62_k1', 0.0)
Parameter('r62_k2', 0.0)
Parameter('r63_k3', 0.0)
Parameter('r64_k1', 0.0)
Parameter('r64_k2', 0.0)
Parameter('r65_k3', 0.0)
Parameter('default_compartment_size', 1e-18)
Parameter('geometry_size', 1e-12)
Parameter('cell_size', 1.0)
Parameter('_geometry_PKC_slash_PKC_minus_Ca_0', 3.72083333333e-17)
Parameter('_geometry_PKC_slash_PKC_minus_DAG_minus_AA_star__0', 4.91366666667e-18)
Parameter('_geometry_PKC_slash_PKC_minus_Ca_minus_AA_star__0', 1.75e-16)
Parameter('_geometry_PKC_slash_PKC_minus_Ca_minus_memb_star__0', 1.3896e-17)
Parameter('_geometry_PKC_slash_PKC_minus_DAG_minus_memb_star__0', 9.43516666667e-21)
Parameter('_geometry_PKC_slash_PKC_minus_basal_star__0', 0.02)
Parameter('_geometry_PKC_slash_PKC_minus_AA_star__0', 1.81333333333e-17)
Parameter('_geometry_PKC_slash_PKC_minus_Ca_minus_DAG_0', 8.46316666667e-23)
Parameter('_geometry_PKC_slash_PKC_minus_DAG_0', 1.16101666667e-16)
Parameter('_geometry_PKC_slash_PKC_minus_DAG_minus_AA_0', 2.51883333333e-19)
Parameter('_geometry_PKC_slash_PKC_minus_cytosolic_0', 1.0)
Parameter('_geometry_MAPK_slash_craf_minus_1_0', 0.2)
Parameter('_geometry_MAPK_slash_MAPKK_0', 0.18)
Parameter('_geometry_MAPK_slash_MAPK_0', 0.36)
Parameter('_geometry_MKP_minus_1_0', 0.0032)
Parameter('_geometry_PPhosphatase2A_0', 0.224)
Parameter('_geometry_PLA2_slash_PLA2_minus_cytosolic_0', 0.4)
Parameter('_geometry_Ras_slash_inact_minus_GEF_0', 0.1)
Parameter('_geometry_Ras_slash_GDP_minus_Ras_0', 0.2)
Parameter('_geometry_Ras_slash_GAP_0', 0.002)
Parameter('_geometry_DAG_0', 11.661)
Parameter('_geometry_Ca_0', 0.08)
Parameter('_geometry_PLA2_slash_APC_0', 30.0)
Parameter('_geometry_temp_minus_PIP2_0', 2.5)
Parameter('_geometry_PKC_minus_active_0', 2.12216666667e-16)

Compartment(name='default_compartment', parent=None, dimension=3, size=default_compartment_size)
Compartment(name='geometry', parent=None, dimension=3, size=geometry_size)
Compartment(name='cell', parent=None, dimension=3, size=cell_size)

Observable('PKC_slash_PKC_minus_Ca', MatchOnce(PKC_slash_PKC_minus_Ca()), match='species')
Observable('PKC_slash_PKC_minus_DAG_minus_AA_star_', MatchOnce(PKC_slash_PKC_minus_DAG_minus_AA_star_()), match='species')
Observable('PKC_slash_PKC_minus_Ca_minus_AA_star_', MatchOnce(PKC_slash_PKC_minus_Ca_minus_AA_star_()), match='species')
Observable('PKC_slash_PKC_minus_Ca_minus_memb_star_', MatchOnce(PKC_slash_PKC_minus_Ca_minus_memb_star_()), match='species')
Observable('PKC_slash_PKC_minus_DAG_minus_memb_star_', MatchOnce(PKC_slash_PKC_minus_DAG_minus_memb_star_()), match='species')
Observable('PKC_slash_PKC_minus_basal_star_', MatchOnce(PKC_slash_PKC_minus_basal_star_()), match='species')
Observable('PKC_slash_PKC_minus_AA_star_', MatchOnce(PKC_slash_PKC_minus_AA_star_()), match='species')
Observable('PKC_slash_PKC_minus_Ca_minus_DAG', MatchOnce(PKC_slash_PKC_minus_Ca_minus_DAG()), match='species')
Observable('PKC_slash_PKC_minus_DAG', MatchOnce(PKC_slash_PKC_minus_DAG()), match='species')
Observable('PKC_slash_PKC_minus_DAG_minus_AA', MatchOnce(PKC_slash_PKC_minus_DAG_minus_AA()), match='species')
Observable('PKC_slash_PKC_minus_cytosolic', MatchOnce(PKC_slash_PKC_minus_cytosolic()), match='species')
Observable('AA', MatchOnce(AA()), match='species')
Observable('PKC_minus_active_slash_PKC_minus_act_minus_raf_slash_PKC_minus_act_minus_raf_cplx', MatchOnce(PKC_minus_active_slash_PKC_minus_act_minus_raf_slash_PKC_minus_act_minus_raf_cplx()), match='species')
Observable('PKC_minus_active_slash_PKC_minus_inact_minus_GAP_slash_PKC_minus_inact_minus_GAP_cplx', MatchOnce(PKC_minus_active_slash_PKC_minus_inact_minus_GAP_slash_PKC_minus_inact_minus_GAP_cplx()), match='species')
Observable('PKC_minus_active_slash_PKC_minus_act_minus_GEF_slash_PKC_minus_act_minus_GEF_cplx', MatchOnce(PKC_minus_active_slash_PKC_minus_act_minus_GEF_slash_PKC_minus_act_minus_GEF_cplx()), match='species')
Observable('MAPK_slash_craf_minus_1', MatchOnce(MAPK_slash_craf_minus_1()), match='species')
Observable('MAPK_slash_craf_minus_1_star_', MatchOnce(MAPK_slash_craf_minus_1_star_()), match='species')
Observable('MAPK_slash_MAPKK', MatchOnce(MAPK_slash_MAPKK()), match='species')
Observable('MAPK_slash_MAPK', MatchOnce(MAPK_slash_MAPK()), match='species')
Observable('MAPK_slash_craf_minus_1_star__star_', MatchOnce(MAPK_slash_craf_minus_1_star__star_()), match='species')
Observable('MAPK_slash_MAPK_minus_tyr', MatchOnce(MAPK_slash_MAPK_minus_tyr()), match='species')
Observable('MAPK_slash_MAPKK_star_', MatchOnce(MAPK_slash_MAPKK_star_()), match='species')
Observable('MAPK_slash_MAPKK_star__slash_MAPKKtyr_slash_MAPKKtyr_cplx', MatchOnce(MAPK_slash_MAPKK_star__slash_MAPKKtyr_slash_MAPKKtyr_cplx()), match='species')
Observable('MAPK_slash_MAPKK_star__slash_MAPKKthr_slash_MAPKKthr_cplx', MatchOnce(MAPK_slash_MAPKK_star__slash_MAPKKthr_slash_MAPKKthr_cplx()), match='species')
Observable('MAPK_slash_MAPKK_minus_ser', MatchOnce(MAPK_slash_MAPKK_minus_ser()), match='species')
Observable('MAPK_slash_Raf_minus_GTP_minus_Ras_star_', MatchOnce(MAPK_slash_Raf_minus_GTP_minus_Ras_star_()), match='species')
Observable('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_slash_Raf_minus_GTP_minus_Ras_star__dot_1_cplx', MatchOnce(MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_slash_Raf_minus_GTP_minus_Ras_star__dot_1_cplx()), match='species')
Observable('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_slash_Raf_minus_GTP_minus_Ras_star__dot_2_cplx', MatchOnce(MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_slash_Raf_minus_GTP_minus_Ras_star__dot_2_cplx()), match='species')
Observable('MAPK_star_', MatchOnce(MAPK_star_()), match='species')
Observable('MAPK_star__slash_MAPK_star__minus_feedback_slash_MAPK_star__minus_feedback_cplx', MatchOnce(MAPK_star__slash_MAPK_star__minus_feedback_slash_MAPK_star__minus_feedback_cplx()), match='species')
Observable('MAPK_star__slash_MAPK_star__slash_MAPK_star__cplx', MatchOnce(MAPK_star__slash_MAPK_star__slash_MAPK_star__cplx()), match='species')
Observable('MKP_minus_1', MatchOnce(MKP_minus_1()), match='species')
Observable('MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_slash_MKP1_minus_tyr_minus_deph_cplx', MatchOnce(MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_slash_MKP1_minus_tyr_minus_deph_cplx()), match='species')
Observable('MKP_minus_1_slash_MKP1_minus_thr_minus_deph_slash_MKP1_minus_thr_minus_deph_cplx', MatchOnce(MKP_minus_1_slash_MKP1_minus_thr_minus_deph_slash_MKP1_minus_thr_minus_deph_cplx()), match='species')
Observable('PPhosphatase2A', MatchOnce(PPhosphatase2A()), match='species')
Observable('PPhosphatase2A_slash_craf_minus_deph_slash_craf_minus_deph_cplx', MatchOnce(PPhosphatase2A_slash_craf_minus_deph_slash_craf_minus_deph_cplx()), match='species')
Observable('PPhosphatase2A_slash_MAPKK_minus_deph_slash_MAPKK_minus_deph_cplx', MatchOnce(PPhosphatase2A_slash_MAPKK_minus_deph_slash_MAPKK_minus_deph_cplx()), match='species')
Observable('PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_slash_MAPKK_minus_deph_minus_ser_cplx', MatchOnce(PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_slash_MAPKK_minus_deph_minus_ser_cplx()), match='species')
Observable('PPhosphatase2A_slash_craf_star__star__minus_deph_slash_craf_star__star__minus_deph_cplx', MatchOnce(PPhosphatase2A_slash_craf_star__star__minus_deph_slash_craf_star__star__minus_deph_cplx()), match='species')
Observable('PLA2_slash_PLA2_minus_cytosolic', MatchOnce(PLA2_slash_PLA2_minus_cytosolic()), match='species')
Observable('PLA2_slash_PLA2_minus_Ca_star_', MatchOnce(PLA2_slash_PLA2_minus_Ca_star_()), match='species')
Observable('PLA2_slash_PLA2_minus_Ca_star__slash_kenz_slash_kenz_cplx', MatchOnce(PLA2_slash_PLA2_minus_Ca_star__slash_kenz_slash_kenz_cplx()), match='species')
Observable('PLA2_slash_PIP2_minus_PLA2_star_', MatchOnce(PLA2_slash_PIP2_minus_PLA2_star_()), match='species')
Observable('PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_slash_kenz_cplx', MatchOnce(PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_slash_kenz_cplx()), match='species')
Observable('PLA2_slash_PIP2_minus_Ca_minus_PLA2_star_', MatchOnce(PLA2_slash_PIP2_minus_Ca_minus_PLA2_star_()), match='species')
Observable('PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx', MatchOnce(PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx()), match='species')
Observable('PLA2_slash_DAG_minus_Ca_minus_PLA2_star_', MatchOnce(PLA2_slash_DAG_minus_Ca_minus_PLA2_star_()), match='species')
Observable('PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx', MatchOnce(PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx()), match='species')
Observable('PLA2_slash_PLA2_star__minus_Ca', MatchOnce(PLA2_slash_PLA2_star__minus_Ca()), match='species')
Observable('PLA2_slash_PLA2_star__minus_Ca_slash_kenz_slash_kenz_cplx', MatchOnce(PLA2_slash_PLA2_star__minus_Ca_slash_kenz_slash_kenz_cplx()), match='species')
Observable('PLA2_slash_PLA2_star_', MatchOnce(PLA2_slash_PLA2_star_()), match='species')
Observable('Ras_slash_inact_minus_GEF', MatchOnce(Ras_slash_inact_minus_GEF()), match='species')
Observable('Ras_slash_GEF_star_', MatchOnce(Ras_slash_GEF_star_()), match='species')
Observable('Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_slash_GEF_star__minus_act_minus_ras_cplx', MatchOnce(Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_slash_GEF_star__minus_act_minus_ras_cplx()), match='species')
Observable('Ras_slash_GTP_minus_Ras', MatchOnce(Ras_slash_GTP_minus_Ras()), match='species')
Observable('Ras_slash_GDP_minus_Ras', MatchOnce(Ras_slash_GDP_minus_Ras()), match='species')
Observable('Ras_slash_GAP_star_', MatchOnce(Ras_slash_GAP_star_()), match='species')
Observable('Ras_slash_GAP', MatchOnce(Ras_slash_GAP()), match='species')
Observable('Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_slash_GAP_minus_inact_minus_ras_cplx', MatchOnce(Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_slash_GAP_minus_inact_minus_ras_cplx()), match='species')
Observable('DAG', MatchOnce(DAG()), match='species')
Observable('Ca', MatchOnce(Ca()), match='species')
Observable('PLA2_slash_APC', MatchOnce(PLA2_slash_APC()), match='species')
Observable('temp_minus_PIP2', MatchOnce(temp_minus_PIP2()), match='species')
Observable('PKC_minus_active', MatchOnce(PKC_minus_active()), match='species')

Expression('PKC_minus_active_ar', -PKC_minus_active_slash_PKC_minus_act_minus_GEF_slash_PKC_minus_act_minus_GEF_cplx - PKC_minus_active_slash_PKC_minus_act_minus_raf_slash_PKC_minus_act_minus_raf_cplx - PKC_minus_active_slash_PKC_minus_inact_minus_GAP_slash_PKC_minus_inact_minus_GAP_cplx + PKC_slash_PKC_minus_AA_star_ + PKC_slash_PKC_minus_Ca_minus_AA_star_ + PKC_slash_PKC_minus_Ca_minus_memb_star_ + PKC_slash_PKC_minus_DAG_minus_AA_star_ + PKC_slash_PKC_minus_DAG_minus_memb_star_ + PKC_slash_PKC_minus_basal_star_)

Rule('PKC_slash_PKC_minus_act_minus_by_minus_Ca', PKC_slash_PKC_minus_cytosolic() ** geometry + Ca() ** geometry <> PKC_slash_PKC_minus_Ca() ** geometry, r1_kf, r1_kb)
Rule('PKC_slash_PKC_minus_act_minus_by_minus_DAG', DAG() ** geometry + PKC_slash_PKC_minus_Ca() ** geometry <> PKC_slash_PKC_minus_Ca_minus_DAG() ** geometry, r2_kf, r2_kb)
Rule('PKC_slash_PKC_minus_Ca_minus_to_minus_memb', PKC_slash_PKC_minus_Ca() ** geometry <> PKC_slash_PKC_minus_Ca_minus_memb_star_() ** geometry, r3_kf, r3_kb)
Rule('PKC_slash_PKC_minus_DAG_minus_to_minus_memb', PKC_slash_PKC_minus_Ca_minus_DAG() ** geometry <> PKC_slash_PKC_minus_DAG_minus_memb_star_() ** geometry, r4_kf, r4_kb)
Rule('PKC_slash_PKC_minus_act_minus_by_minus_Ca_minus_AA', PKC_slash_PKC_minus_Ca() ** geometry + AA() ** geometry <> PKC_slash_PKC_minus_Ca_minus_AA_star_() ** geometry, r5_kf, r5_kb)
Rule('PKC_slash_PKC_minus_act_minus_by_minus_DAG_minus_AA', PKC_slash_PKC_minus_DAG_minus_AA() ** geometry <> PKC_slash_PKC_minus_DAG_minus_AA_star_() ** geometry, r6_kf, r6_kb)
Rule('PKC_slash_PKC_minus_basal_minus_act', PKC_slash_PKC_minus_cytosolic() ** geometry <> PKC_slash_PKC_minus_basal_star_() ** geometry, r7_kf, r7_kb)
Rule('PKC_slash_PKC_minus_act_minus_by_minus_AA', AA() ** geometry + PKC_slash_PKC_minus_cytosolic() ** geometry <> PKC_slash_PKC_minus_AA_star_() ** geometry, r8_kf, r8_kb)
Rule('PKC_slash_PKC_minus_n_minus_DAG', PKC_slash_PKC_minus_cytosolic() ** geometry + DAG() ** geometry <> PKC_slash_PKC_minus_DAG() ** geometry, r9_kf, r9_kb)
Rule('PKC_slash_PKC_minus_n_minus_DAG_minus_AA', PKC_slash_PKC_minus_DAG() ** geometry + AA() ** geometry <> PKC_slash_PKC_minus_DAG_minus_AA() ** geometry, r10_kf, r10_kb)
Rule('Ras_minus_act_minus_craf', MAPK_slash_craf_minus_1_star_() ** geometry + Ras_slash_GTP_minus_Ras() ** geometry <> MAPK_slash_Raf_minus_GTP_minus_Ras_star_() ** geometry, r11_kf, r11_kb)
Rule('PLA2_slash_PLA2_minus_Ca_minus_act', PLA2_slash_PLA2_minus_cytosolic() ** geometry + Ca() ** geometry <> PLA2_slash_PLA2_minus_Ca_star_() ** geometry, r12_kf, r12_kb)
Rule('PLA2_slash_PIP2_minus_PLA2_minus_act', temp_minus_PIP2() ** geometry + PLA2_slash_PLA2_minus_cytosolic() ** geometry <> PLA2_slash_PIP2_minus_PLA2_star_() ** geometry, r13_kf, r13_kb)
Rule('PLA2_slash_PIP2_minus_Ca_minus_PLA2_minus_act', temp_minus_PIP2() ** geometry + PLA2_slash_PLA2_minus_Ca_star_() ** geometry <> PLA2_slash_PIP2_minus_Ca_minus_PLA2_star_() ** geometry, r14_kf, r14_kb)
Rule('PLA2_slash_DAG_minus_Ca_minus_PLA2_minus_act', DAG() ** geometry + PLA2_slash_PLA2_minus_Ca_star_() ** geometry <> PLA2_slash_DAG_minus_Ca_minus_PLA2_star_() ** geometry, r15_kf, r15_kb)
Rule('PLA2_slash_Degrade_minus_AA', AA() ** geometry <> PLA2_slash_APC() ** geometry, r16_kf, r16_kb)
Rule('PLA2_slash_PLA2_star__minus_Ca_minus_act', PLA2_slash_PLA2_star_() ** geometry + Ca() ** geometry <> PLA2_slash_PLA2_star__minus_Ca() ** geometry, r17_kf, r17_kb)
Rule('PLA2_slash_dephosphorylate_minus_PLA2_star_', PLA2_slash_PLA2_star_() ** geometry <> PLA2_slash_PLA2_minus_cytosolic() ** geometry, r18_kf, r18_kb)
Rule('Ras_slash_dephosph_minus_GEF', Ras_slash_GEF_star_() ** geometry <> Ras_slash_inact_minus_GEF() ** geometry, r19_kf, r19_kb)
Rule('Ras_slash_Ras_minus_intrinsic_minus_GTPase', Ras_slash_GTP_minus_Ras() ** geometry <> Ras_slash_GDP_minus_Ras() ** geometry, r20_kf, r20_kb)
Rule('Ras_slash_dephosph_minus_GAP', Ras_slash_GAP_star_() ** geometry <> Ras_slash_GAP() ** geometry, r21_kf, r21_kb)
Rule('PKC_minus_active_slash_PKC_minus_act_minus_raf_1', MAPK_slash_craf_minus_1() ** geometry + PKC_minus_active() ** geometry <> PKC_minus_active_slash_PKC_minus_act_minus_raf_slash_PKC_minus_act_minus_raf_cplx() ** geometry, r22_k1, r22_k2)
Rule('PKC_minus_active_slash_PKC_minus_act_minus_raf_2', PKC_minus_active_slash_PKC_minus_act_minus_raf_slash_PKC_minus_act_minus_raf_cplx() ** geometry >> MAPK_slash_craf_minus_1_star_() ** geometry + PKC_minus_active() ** geometry, r23_k3)
Rule('PKC_minus_active_slash_PKC_minus_inact_minus_GAP_1', Ras_slash_GAP() ** geometry + PKC_minus_active() ** geometry <> PKC_minus_active_slash_PKC_minus_inact_minus_GAP_slash_PKC_minus_inact_minus_GAP_cplx() ** geometry, r24_k1, r24_k2)
Rule('PKC_minus_active_slash_PKC_minus_inact_minus_GAP_2', PKC_minus_active_slash_PKC_minus_inact_minus_GAP_slash_PKC_minus_inact_minus_GAP_cplx() ** geometry >> Ras_slash_GAP_star_() ** geometry + PKC_minus_active() ** geometry, r25_k3)
Rule('PKC_minus_active_slash_PKC_minus_act_minus_GEF_1', Ras_slash_inact_minus_GEF() ** geometry + PKC_minus_active() ** geometry <> PKC_minus_active_slash_PKC_minus_act_minus_GEF_slash_PKC_minus_act_minus_GEF_cplx() ** geometry, r26_k1, r26_k2)
Rule('PKC_minus_active_slash_PKC_minus_act_minus_GEF_2', PKC_minus_active_slash_PKC_minus_act_minus_GEF_slash_PKC_minus_act_minus_GEF_cplx() ** geometry >> Ras_slash_GEF_star_() ** geometry + PKC_minus_active() ** geometry, r27_k3)
Rule('MAPK_slash_MAPKK_star__slash_MAPKKtyr_1', MAPK_slash_MAPK() ** geometry + MAPK_slash_MAPKK_star_() ** geometry <> MAPK_slash_MAPKK_star__slash_MAPKKtyr_slash_MAPKKtyr_cplx() ** geometry, r28_k1, r28_k2)
Rule('MAPK_slash_MAPKK_star__slash_MAPKKtyr_2', MAPK_slash_MAPKK_star__slash_MAPKKtyr_slash_MAPKKtyr_cplx() ** geometry >> MAPK_slash_MAPK_minus_tyr() ** geometry + MAPK_slash_MAPKK_star_() ** geometry, r29_k3)
Rule('MAPK_slash_MAPKK_star__slash_MAPKKthr_1', MAPK_slash_MAPK_minus_tyr() ** geometry + MAPK_slash_MAPKK_star_() ** geometry <> MAPK_slash_MAPKK_star__slash_MAPKKthr_slash_MAPKKthr_cplx() ** geometry, r30_k1, r30_k2)
Rule('MAPK_slash_MAPKK_star__slash_MAPKKthr_2', MAPK_slash_MAPKK_star__slash_MAPKKthr_slash_MAPKKthr_cplx() ** geometry >> MAPK_star_() ** geometry + MAPK_slash_MAPKK_star_() ** geometry, r31_k3)
Rule('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_1', MAPK_slash_MAPKK() ** geometry + MAPK_slash_Raf_minus_GTP_minus_Ras_star_() ** geometry <> MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_slash_Raf_minus_GTP_minus_Ras_star__dot_1_cplx() ** geometry, r32_k1, r32_k2)
Rule('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_2', MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_1_slash_Raf_minus_GTP_minus_Ras_star__dot_1_cplx() ** geometry >> MAPK_slash_MAPKK_minus_ser() ** geometry + MAPK_slash_Raf_minus_GTP_minus_Ras_star_() ** geometry, r33_k3)
Rule('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_1', MAPK_slash_MAPKK_minus_ser() ** geometry + MAPK_slash_Raf_minus_GTP_minus_Ras_star_() ** geometry <> MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_slash_Raf_minus_GTP_minus_Ras_star__dot_2_cplx() ** geometry, r34_k1, r34_k2)
Rule('MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_2', MAPK_slash_Raf_minus_GTP_minus_Ras_star__slash_Raf_minus_GTP_minus_Ras_star__dot_2_slash_Raf_minus_GTP_minus_Ras_star__dot_2_cplx() ** geometry >> MAPK_slash_MAPKK_star_() ** geometry + MAPK_slash_Raf_minus_GTP_minus_Ras_star_() ** geometry, r35_k3)
Rule('MAPK_star__slash_MAPK_star__minus_feedback_1', MAPK_slash_craf_minus_1_star_() ** geometry + MAPK_star_() ** geometry <> MAPK_star__slash_MAPK_star__minus_feedback_slash_MAPK_star__minus_feedback_cplx() ** geometry, r36_k1, r36_k2)
Rule('MAPK_star__slash_MAPK_star__minus_feedback_2', MAPK_star__slash_MAPK_star__minus_feedback_slash_MAPK_star__minus_feedback_cplx() ** geometry >> MAPK_slash_craf_minus_1_star__star_() ** geometry + MAPK_star_() ** geometry, r37_k3)
Rule('MAPK_star__slash_MAPK_star__1', PLA2_slash_PLA2_minus_cytosolic() ** geometry + MAPK_star_() ** geometry <> MAPK_star__slash_MAPK_star__slash_MAPK_star__cplx() ** geometry, r38_k1, r38_k2)
Rule('MAPK_star__slash_MAPK_star__2', MAPK_star__slash_MAPK_star__slash_MAPK_star__cplx() ** geometry >> PLA2_slash_PLA2_star_() ** geometry + MAPK_star_() ** geometry, r39_k3)
Rule('MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_1', MAPK_slash_MAPK_minus_tyr() ** geometry + MKP_minus_1() ** geometry <> MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_slash_MKP1_minus_tyr_minus_deph_cplx() ** geometry, r40_k1, r40_k2)
Rule('MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_2', MKP_minus_1_slash_MKP1_minus_tyr_minus_deph_slash_MKP1_minus_tyr_minus_deph_cplx() ** geometry >> MAPK_slash_MAPK() ** geometry + MKP_minus_1() ** geometry, r41_k3)
Rule('MKP_minus_1_slash_MKP1_minus_thr_minus_deph_1', MAPK_star_() ** geometry + MKP_minus_1() ** geometry <> MKP_minus_1_slash_MKP1_minus_thr_minus_deph_slash_MKP1_minus_thr_minus_deph_cplx() ** geometry, r42_k1, r42_k2)
Rule('MKP_minus_1_slash_MKP1_minus_thr_minus_deph_2', MKP_minus_1_slash_MKP1_minus_thr_minus_deph_slash_MKP1_minus_thr_minus_deph_cplx() ** geometry >> MAPK_slash_MAPK_minus_tyr() ** geometry + MKP_minus_1() ** geometry, r43_k3)
Rule('PPhosphatase2A_slash_craf_minus_deph_1', MAPK_slash_craf_minus_1_star_() ** geometry + PPhosphatase2A() ** geometry <> PPhosphatase2A_slash_craf_minus_deph_slash_craf_minus_deph_cplx() ** geometry, r44_k1, r44_k2)
Rule('PPhosphatase2A_slash_craf_minus_deph_2', PPhosphatase2A_slash_craf_minus_deph_slash_craf_minus_deph_cplx() ** geometry >> MAPK_slash_craf_minus_1() ** geometry + PPhosphatase2A() ** geometry, r45_k3)
Rule('PPhosphatase2A_slash_MAPKK_minus_deph_1', MAPK_slash_MAPKK_star_() ** geometry + PPhosphatase2A() ** geometry <> PPhosphatase2A_slash_MAPKK_minus_deph_slash_MAPKK_minus_deph_cplx() ** geometry, r46_k1, r46_k2)
Rule('PPhosphatase2A_slash_MAPKK_minus_deph_2', PPhosphatase2A_slash_MAPKK_minus_deph_slash_MAPKK_minus_deph_cplx() ** geometry >> MAPK_slash_MAPKK_minus_ser() ** geometry + PPhosphatase2A() ** geometry, r47_k3)
Rule('PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_1', MAPK_slash_MAPKK_minus_ser() ** geometry + PPhosphatase2A() ** geometry <> PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_slash_MAPKK_minus_deph_minus_ser_cplx() ** geometry, r48_k1, r48_k2)
Rule('PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_2', PPhosphatase2A_slash_MAPKK_minus_deph_minus_ser_slash_MAPKK_minus_deph_minus_ser_cplx() ** geometry >> MAPK_slash_MAPKK() ** geometry + PPhosphatase2A() ** geometry, r49_k3)
Rule('PPhosphatase2A_slash_craf_star__star__minus_deph_1', MAPK_slash_craf_minus_1_star__star_() ** geometry + PPhosphatase2A() ** geometry <> PPhosphatase2A_slash_craf_star__star__minus_deph_slash_craf_star__star__minus_deph_cplx() ** geometry, r50_k1, r50_k2)
Rule('PPhosphatase2A_slash_craf_star__star__minus_deph_2', PPhosphatase2A_slash_craf_star__star__minus_deph_slash_craf_star__star__minus_deph_cplx() ** geometry >> MAPK_slash_craf_minus_1_star_() ** geometry + PPhosphatase2A() ** geometry, r51_k3)
Rule('PLA2_slash_PLA2_minus_Ca_star__slash_kenz_1', PLA2_slash_APC() ** geometry + PLA2_slash_PLA2_minus_Ca_star_() ** geometry <> PLA2_slash_PLA2_minus_Ca_star__slash_kenz_slash_kenz_cplx() ** geometry, r52_k1, r52_k2)
Rule('PLA2_slash_PLA2_minus_Ca_star__slash_kenz_2', PLA2_slash_PLA2_minus_Ca_star__slash_kenz_slash_kenz_cplx() ** geometry >> AA() ** geometry + PLA2_slash_PLA2_minus_Ca_star_() ** geometry, r53_k3)
Rule('PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_1', PLA2_slash_APC() ** geometry + PLA2_slash_PIP2_minus_PLA2_star_() ** geometry <> PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_slash_kenz_cplx() ** geometry, r54_k1, r54_k2)
Rule('PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_2', PLA2_slash_PIP2_minus_PLA2_star__slash_kenz_slash_kenz_cplx() ** geometry >> AA() ** geometry + PLA2_slash_PIP2_minus_PLA2_star_() ** geometry, r55_k3)
Rule('PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_1', PLA2_slash_APC() ** geometry + PLA2_slash_PIP2_minus_Ca_minus_PLA2_star_() ** geometry <> PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx() ** geometry, r56_k1, r56_k2)
Rule('PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_2', PLA2_slash_PIP2_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx() ** geometry >> AA() ** geometry + PLA2_slash_PIP2_minus_Ca_minus_PLA2_star_() ** geometry, r57_k3)
Rule('PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_1', PLA2_slash_APC() ** geometry + PLA2_slash_DAG_minus_Ca_minus_PLA2_star_() ** geometry <> PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx() ** geometry, r58_k1, r58_k2)
Rule('PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_2', PLA2_slash_DAG_minus_Ca_minus_PLA2_star__slash_kenz_slash_kenz_cplx() ** geometry >> AA() ** geometry + PLA2_slash_DAG_minus_Ca_minus_PLA2_star_() ** geometry, r59_k3)
Rule('PLA2_slash_PLA2_star__minus_Ca_slash_kenz_1', PLA2_slash_APC() ** geometry + PLA2_slash_PLA2_star__minus_Ca() ** geometry <> PLA2_slash_PLA2_star__minus_Ca_slash_kenz_slash_kenz_cplx() ** geometry, r60_k1, r60_k2)
Rule('PLA2_slash_PLA2_star__minus_Ca_slash_kenz_2', PLA2_slash_PLA2_star__minus_Ca_slash_kenz_slash_kenz_cplx() ** geometry >> AA() ** geometry + PLA2_slash_PLA2_star__minus_Ca() ** geometry, r61_k3)
Rule('Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_1', Ras_slash_GDP_minus_Ras() ** geometry + Ras_slash_GEF_star_() ** geometry <> Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_slash_GEF_star__minus_act_minus_ras_cplx() ** geometry, r62_k1, r62_k2)
Rule('Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_2', Ras_slash_GEF_star__slash_GEF_star__minus_act_minus_ras_slash_GEF_star__minus_act_minus_ras_cplx() ** geometry >> Ras_slash_GTP_minus_Ras() ** geometry + Ras_slash_GEF_star_() ** geometry, r63_k3)
Rule('Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_1', Ras_slash_GTP_minus_Ras() ** geometry + Ras_slash_GAP() ** geometry <> Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_slash_GAP_minus_inact_minus_ras_cplx() ** geometry, r64_k1, r64_k2)
Rule('Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_2', Ras_slash_GAP_slash_GAP_minus_inact_minus_ras_slash_GAP_minus_inact_minus_ras_cplx() ** geometry >> Ras_slash_GDP_minus_Ras() ** geometry + Ras_slash_GAP() ** geometry, r65_k3)

Initial((PKC_slash_PKC_minus_Ca() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_Ca_0)
Initial((PKC_slash_PKC_minus_DAG_minus_AA_star_() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_DAG_minus_AA_star__0)
Initial((PKC_slash_PKC_minus_Ca_minus_AA_star_() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_Ca_minus_AA_star__0)
Initial((PKC_slash_PKC_minus_Ca_minus_memb_star_() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_Ca_minus_memb_star__0)
Initial((PKC_slash_PKC_minus_DAG_minus_memb_star_() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_DAG_minus_memb_star__0)
Initial((PKC_slash_PKC_minus_basal_star_() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_basal_star__0)
Initial((PKC_slash_PKC_minus_AA_star_() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_AA_star__0)
Initial((PKC_slash_PKC_minus_Ca_minus_DAG() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_Ca_minus_DAG_0)
Initial((PKC_slash_PKC_minus_DAG() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_DAG_0)
Initial((PKC_slash_PKC_minus_DAG_minus_AA() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_DAG_minus_AA_0)
Initial((PKC_slash_PKC_minus_cytosolic() ** geometry) ** geometry, _geometry_PKC_slash_PKC_minus_cytosolic_0)
Initial((MAPK_slash_craf_minus_1() ** geometry) ** geometry, _geometry_MAPK_slash_craf_minus_1_0)
Initial((MAPK_slash_MAPKK() ** geometry) ** geometry, _geometry_MAPK_slash_MAPKK_0)
Initial((MAPK_slash_MAPK() ** geometry) ** geometry, _geometry_MAPK_slash_MAPK_0)
Initial((MKP_minus_1() ** geometry) ** geometry, _geometry_MKP_minus_1_0)
Initial((PPhosphatase2A() ** geometry) ** geometry, _geometry_PPhosphatase2A_0)
Initial((PLA2_slash_PLA2_minus_cytosolic() ** geometry) ** geometry, _geometry_PLA2_slash_PLA2_minus_cytosolic_0)
Initial((Ras_slash_inact_minus_GEF() ** geometry) ** geometry, _geometry_Ras_slash_inact_minus_GEF_0)
Initial((Ras_slash_GDP_minus_Ras() ** geometry) ** geometry, _geometry_Ras_slash_GDP_minus_Ras_0)
Initial((Ras_slash_GAP() ** geometry) ** geometry, _geometry_Ras_slash_GAP_0)
Initial((DAG() ** geometry) ** geometry, _geometry_DAG_0)
Initial((Ca() ** geometry) ** geometry, _geometry_Ca_0)
Initial((PLA2_slash_APC() ** geometry) ** geometry, _geometry_PLA2_slash_APC_0)
Initial((temp_minus_PIP2() ** geometry) ** geometry, _geometry_temp_minus_PIP2_0)
Initial((PKC_minus_active() ** geometry) ** geometry, _geometry_PKC_minus_active_0)

